const enStrings = {
  addToCart:'Add to cart',
  enterNumber: 'enter Number',
  catsStore: 'CatsStore',
  dogsStore: 'DogsStore',
  cart: 'Cart',
  priceTag: "₪",
  price: 'price',
  empty: "Empty",
  DryFood: "Dry Food",
  meat: "MEAT",
  TOYS: "TOYS", 
  Clothes: "Clothes",
  Sprays: "Sprays",
  leash: "Leash",
  display: "display",
  accessories: "Accessories",
  toilet: 'Toilet',
  brands: 'brands',
  selectABrand: 'select a brand',
  sale: 'Sale',
  treats: 'Treats',
  perfume: 'perfume',
  bowl: 'BOWL',
  clearCart: 'Clear cart',
};

const heStrings = {
  addToCart: 'הוסף לעגלה',
  enterNumber: 'הכנס מספר',
  catsStore: 'חנות חתולים',
  dogsStore: 'חנות כלבים',
  cart: "עגלה",
  priceTag: "₪",
  price: 'מחיר',
  empty: "ריק",
  DryFood: "אוכל יבש",
  meat: "בשר",
  TOYS: "צעצועים",
  Clothes: "בגדים",
  Sprays: "תרסיסים",
  leash: "רצועה",
  display: "תצוגה",
  accessories: "אביזרים",
  toilet: 'שירותים',
  brands: 'מותגים',
  selectABrand: 'בחר מותג',
  sale: 'מכירה',
  treats: 'חטיפים',
  perfume: 'בושם',
  bowl: 'קערה',
  clearCart: 'נקה עגלה', 
};

const arStrings = {
  addToCart: 'أضف إلى السلة',
  enterNumber:'أدخل رقم',
  catsStore: 'متجر القطط',
  dogsStore: 'متجر الكلاب',
  cart: "سلة",
  priceTag: "₪",
  price: 'السعر',
  empty: "فارغ",
  DryFood: "طعام جاف",
  meat: "لحم",
  TOYS: "ألعاب",
  Clothes: "ملابس",
  Sprays: "بخاخات",
  leash: "مقود",
  display: "عرض",
  accessories: "إكسسوارات",
  toilet: 'مرحاض',
  brands: 'علامات تجارية',
  selectABrand: 'اختر علامة تجارية',
  sale: 'تخفيض',
  treats: 'حلويات',
  perfume: 'عطر',
  bowl: 'وعاء',
  clearCart: 'مسح العربة', 
};

export { enStrings, heStrings, arStrings };
