const enStrings = {
  addToCart: 'Add to cart',
  enterNumber: 'Enter number',
  catsStore: 'Cat',
  dogsStore: 'Dog', 
  cart: 'Cart',
  priceTag: "₪",
  price: 'Price',
  empty: "Empty",
  DryFood: "Dry Food",
  meat: "Meat",
  TOYS: "Toys",
  Clothes: "Clothes",
  Sprays: "Sprays",
  leash: "Leash",
  display: "Display",
  accessories: "Accessories",
  toilet: 'Toilet',
  brands: 'Brands',
  selectABrand: 'Select a brand',
  sale: 'Sale',
  treats: 'Treats',
  perfume: 'Perfume',
  bowl: 'Bowl',
  clearCart: 'Clear cart',
};

const heStrings = {
  addToCart: 'הוסף לעגלה',
  enterNumber: 'הכנס מספר',
  catsStore: 'חתול', 
  dogsStore: 'כלב', 
  cart: "עגלה",
  priceTag: "₪",
  price: 'מחיר',
  empty: "ריק",
  DryFood: "אוכל יבש",
  meat: "בשר",
  TOYS: "צעצועים",
  Clothes: "בגדים",
  Sprays: "תרסיסים",
  leash: "רצועה",
  display: "תצוגה",
  accessories: "אביזרים",
  toilet: 'שירותים',
  brands: 'מותגים',
  selectABrand: 'בחר מותג',
  sale: 'מכירה',
  treats: 'חטיפים',
  perfume: 'בושם',
  bowl: 'קערה',
  clearCart: 'נקה עגלה',
};

const arStrings = {
  addToCart: 'أضف إلى السلة',
  enterNumber: 'أدخل رقم',
  catsStore: 'قط',
  dogsStore: 'كلب', 
  cart: "سلة",
  priceTag: "₪",
  price: 'السعر',
  empty: "فارغ",
  DryFood: "طعام جاف",
  meat: "لحم",
  TOYS: "ألعاب",
  Clothes: "ملابس",
  Sprays: "بخاخات",
  leash: "مقود",
  display: "عرض",
  accessories: "إكسسوارات",
  toilet: 'مرحاض',
  brands: 'علامات تجارية',
  selectABrand: 'اختر علامة تجارية',
  sale: 'تخفيض',
  treats: 'حلويات',
  perfume: 'عطر',
  bowl: 'وعاء',
  clearCart: 'مسح العربة',
};

export { enStrings, heStrings, arStrings };
