const enStrings = {
  loginMessage: 'do you want to sign in?',
  productAdded: 'Product added',
  searchKeys: 'search keys',
  inStock: 'In Stock',
  dis: 'description',
  selectedpets: 'selected pets',
  row: 'row',
  selectedRow: 'selected row',
  taste: 'Taste',
  amount: 'amount',
  weight: 'weight',
  saleAmount: 'sale Amount',
  salePrice: 'sale Price',
  cat: 'cat',
  dog: 'dog',
  petType: 'pet type',
  editProduct: 'edit Product',
  saveChanges: 'Save changes',
  savingChanges: 'saving changes',
  category: 'Category',
  fillthefield: 'Please fill out the following fields',
  Brand: 'Brand',
  amountError: ' sale amount is higher than  sale price',
  name: 'name',
  brand: 'brand',
  delMessage: 'do you want to dellete the item?',
  addToCart: 'Add to cart',
  enterNumber: 'Enter number',
  catsStore: 'Cat',
  dogsStore: 'Dog',
  cart: 'Cart',
  priceTag: '₪',
  price: 'Price',
  empty: 'Empty',
  DryFood: 'Dry Food',
  meat: 'Meat',
  TOYS: 'Toys',
  Clothes: 'Clothes',
  Sprays: 'Sprays',
  leash: 'Leash',
  display: 'Display',
  accessories: 'Accessories',
  toilet: 'Toilet',
  brands: 'Brands',
  selectABrand: 'Select a brand',
  sale: 'Sale',
  treats: 'Treats',
  perfume: 'Perfume',
  bowl: 'Bowl',
  clearCart: 'Clear cart',
  image: 'image',
  selectAll: 'Select All',
  seeAllButton: 'See all',
  itemaddsucces: 'Item added to cart successfully',
  selectAProduct: 'Please select a product',
  delUser: 'do you want to dellete your account?',
};

const heStrings = {
  addToCart: 'הוסף לעגלה',
  enterNumber: 'הכנס מספר',
  catsStore: 'חתול',
  dogsStore: 'כלב',
  cart: 'עגלה',
  priceTag: '₪',
  price: 'מחיר',
  empty: 'ריק',
  DryFood: 'אוכל יבש',
  meat: 'בשר',
  TOYS: 'צעצועים',
  Clothes: 'בגדים',
  Sprays: 'תרסיסים',
  leash: 'רצועה',
  display: 'תצוגה',
  accessories: 'אביזרים',
  toilet: 'שירותים',
  brands: 'מותגים',
  selectABrand: 'בחר מותג',
  sale: 'מכירה',
  treats: 'חטיפים',
  perfume: 'בושם',
  bowl: 'קערה',
  clearCart: 'נקה עגלה',
  fillthefield: 'אנא מלא את השדות הבאים',
  delMessage: 'האם אתה רוצה למחוק את הפריט?',
  selectedpets: 'חיות מחמד שנבחרו',
  row: 'שורה',
  selectedRow: 'שורה נבחרת',
  taste: 'טעם',
  price: 'מחיר',
  weight: 'משקל',
  saleAmount: 'כמות מבצע',
  salePrice: 'מחיר מבצע',
  cat: 'חתול',
  dog: 'כלב',
  petType: 'סוג חיית מחמד',
  editProduct: 'ערוך מוצר',
  saveChanges: 'שמור שינויים',
  savingChanges: 'שומר שינויים',
  brand: 'מותג ',
  category: 'קטגוריה',
  name: 'שם',
  price: 'מחיר',
  amount: 'כמות',
  amountError: 'כמות המכירה גבוהה יותר ממחיר המכירה',
  image: 'תמונה',
  selectAll: 'בחר הכל',
  dis: 'תיאור',
  inStock: 'זמין במלאי',
  searchKeys: 'מילות חיפוש',
  seeAllButton: 'כל המוצרים',
  productAdded: 'המוצר נוסף',
  itemaddsucces: 'פריט נוסף לסל בהצלחה',
  selectAProduct: 'אנא בחר מוצר',
  delUser: 'האם אתה רוצה למחוק את החשבון שלך?',
  loginMessage: ' האם אתה רוצה להיכנס?',
};

const arStrings = {
  loginMessage: 'هل تريد تسجيل الدخول؟',
  delUser: 'هل تريد حذف حسابك؟',
  selectAProduct: 'الرجاء اختيار منتج',
  itemaddsucces: 'تم إضافة العنصر إلى السلة بنجاح',
  productAdded: 'تم إضافة المنتج',
  inStock: 'متوفر',
  dis: 'وصف',
  amountError: 'كمية التخفيض أكبر من سعر التخفيض',
  delMessage: 'هل تريد حذف الغرض',
  addToCart: 'أضف إلى السلة',
  enterNumber: 'أدخل رقم',
  catsStore: 'قط',
  dogsStore: 'كلب',
  cart: 'سلة',
  priceTag: '₪',
  price: 'السعر',
  empty: 'فارغ',
  DryFood: 'طعام جاف',
  meat: 'لحم',
  TOYS: 'ألعاب',
  Clothes: 'ملابس',
  Sprays: 'بخاخات',
  leash: 'مقود',
  display: 'عرض',
  accessories: 'إكسسوارات',
  toilet: 'مرحاض',
  brands: 'علامات تجارية',
  selectABrand: 'اختر علامة تجارية',
  sale: 'تخفيض',
  treats: 'حلويات',
  perfume: 'عطر',
  bowl: 'وعاء',
  clearCart: 'مسح العربة',
  name: 'اسم',
  price: 'سعر',

  selectedpets: 'الحيوانات الأليفة المختارة',
  row: 'صف',
  selectedRow: ' الريف',
  taste: 'الطعم',
  price: 'السعر',
  weight: 'الوزن',
  saleAmount: 'كمية التخفيض',
  salePrice: 'سعر التخفيض',
  cat: 'قط',
  dog: 'كلب',
  petType: 'نوع الحيوان الأليف',
  editProduct: 'تعديل المنتج',
  saveChanges: 'حفظ التغييرات',
  savingChanges: 'جارٍ حفظ التغييرات',
  brand: ' الشركه',
  category: 'فئة',
  fillthefield: 'يرجى ملء الصفات التالية',
  amount: 'كميه',
  image: 'صوره',
  selectAll: 'اختر الكل',
  searchKeys: 'مفاتيح البحث',
  seeAllButton: 'كل المنتجات',
};

export {enStrings, heStrings, arStrings};
