[build]
  command = "npx expo export"
  publish = "web-build"

[[headers]]
  for = "/*"
    [headers.values]
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Cross-Origin-Embedder-Policy = "require-corp"
